name: Deploy
on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LLK/scratch-gui
          ref: develop
      - run: npm install
      - uses: actions/checkout@v2
        with:
          path: ./tmpose2scratch
      - run: sh ./tmpose2scratch/install.sh
      - run: sh ./tmpose2scratch/add_ga_tracking_code.sh
      - run: npm run build
      - run: cp ./tmpose2scratch/index.html ./build/index.html
      - run: cp ./tmpose2scratch/favicon.ico ./build/static/favicon.ico
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
      - uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_USERNAME: TM2Scratch
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'tmpose2scratch is deployed! :rocket:'
          SLACK_ICON: https://champierre.github.io/tm2scratch/static/favicon.ico
